name: EKS deployment workflow

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Fastfoof EKS cluster'
        required: true
        default: 'eks-cluster'
      action:
        description: 'Deploy ou Destroy'
        required: true
        default: 'deploy'
        type: choice
        options:
          - terraform-apply
          - terraform-destroy

jobs:
  terraform-apply:
    if: ${{ github.event.inputs.action == 'terraform-apply' }}
    runs-on: ubuntu-latest
    env:
      REGION_DEFAULT: us-east-1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION_DEFAULT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform validade
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -output=plan.out

    - name: Terraform Apply
      run: terraform apply plan.out 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-destroy: 
    if: ${{ github.event.inputs.action == 'terraform-destroy' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0


    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}