name: AKS deployment workflow

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Fastfoof AKS cluster'
        required: true
        default: 'aks-cluster'
      action:
        description: 'Deploy ou Destroy'
        required: true
        default: 'deploy'
        type: choice
        options:
          - terraform-deploy
          - terraform-destroy

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.REGION_DEFAULT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform validade
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -output=plan.out

    - name: Terraform Apply
      run: terraform apply plan.out 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload Terraform state
      uses: actions/upload-artifact@v2
      with:
        name: terraform-state
        path: ./terraform.tfstate
        
    - name: Workspace view
      run: ls -R

  terraform-destroy: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
        
    - name: Download Terraform state
      uses: actions/download-artifact@v2
      with:
        name: terraform-state
        path: ./terraform.tfstate

    - name: Workspace view
      run: ls -R

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}