name: Deploy Fastfood
on:
  workflow_dispatch:

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "cluster-fastfood"
jobs:
  deploy:
    name: Deploy AWS Academy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}

      - name: Kube Apply ConfigMap
        run: kubectl apply -f k8s/configmap.yaml
      - name: Kube Apply Secrets
        run: kubectl apply  k8s/secrets.yaml
      - name: Kube Apply Mysql Configmap
        run: kubectl apply  k8s/mysql-configmap.yaml
      - name: Kube Apply App
        run: kubectl apply  k8s/deployment.yaml
      - name: Kube Apply LoadBalancer
        run: kubectl apply  k8s/load-balancer.yaml
  
      
